Repository kserve/modelmesh-serving, pull requests merged in 2021-10, with the labels that each got.

#39 docs: Sync internal documentation
  README.md
  docs/README.md
  docs/architecture/README.md
  docs/architecture/isolation.md
  docs/architecture/secrets-and-cms.md
  docs/configuration.md
  docs/configuration/README.md
  docs/configuration/built-in-runtimes.md
  docs/images/0.2.0-highlevel.png
  docs/images/rt-builtin.png
  docs/images/rt-custom-direct.png
  docs/images/rt-custom-full.png
  docs/images/rt-custom-nopull.png
  docs/images/rt-custom-pull.png
  docs/images/secrets-and-cms.png
  docs/inference/data-types-mapping.md
  docs/inference/ks-v2-grpc.md
  docs/install/README.md
  docs/install/install-script.md
  docs/model-types/README.md
  docs/model-types/advanced-configuration.md
  docs/model-types/lightgbm.md
  docs/model-types/onnx.md
  docs/model-types/pytorch.md
  docs/model-types/sklearn.md
  docs/model-types/tensorflow.md
  docs/model-types/xgboost.md
  docs/predictors/README.md
  docs/predictors/predictor-cr.md
  docs/predictors/predictor-spec.md
  docs/predictors/run-inference.md
  docs/predictors/schema.md
  docs/predictors/setup-storage.md
  docs/production-use/README.md
  docs/production-use/scaling.md
  docs/quickstart.md
  docs/runtimes/README.md
  docs/runtimes/custom_runtimes.md
  docs/runtimes/mlserver_custom.md
  docs/troubleshooting.md
Labels: lgtm, approved

#40 chore: Add release process items
  .github/workflows/build-and-push.yml
  release/RELEASE_PROCESS.md
Labels: lgtm, approved, ok-to-test

#27 feat: Add preliminary REST inferencing support via proxy container
  config/default/config-defaults.yaml
  controllers/config.go
  controllers/modelmesh/const.go
  controllers/modelmesh/modelmesh.go
  controllers/modelmesh/proxy.go
  controllers/modelmesh/tls.go
  controllers/predictor_controller.go
  controllers/service_controller.go
  controllers/servingruntime_controller.go
  controllers/servingruntime_controller_test.go
  controllers/testdata/servingruntime_controller.golden
  controllers/testdata/test-config-defaults.yaml
  main.go
  pkg/mmesh/modelmesh_service.go
Labels: approved

#41 Add component versions doc
  README.md
  docs/component-versions.md
Labels: lgtm, approved

#43 fix: Add default REST port to runtime NetworkPolicy
  config/rbac/networkpolicy-runtimes.yaml
Labels: lgtm, approved

#45 Internal Sync - FVT refactoring
  fvt/fvt_suite_test.go
  fvt/fvtclient.go
  fvt/globals.go
  fvt/helpers.go
  fvt/inference.go
  fvt/predictor_test.go
  fvt/scale_to_zero_test.go
  fvt/utils.go
Labels: approved

#47 docs: Add info about InferenceService deployment
  docs/inferenceservice.md
  docs/quickstart.md
Labels: lgtm, approved

#50 [release-0.7] Update controller image tag
  config/manager/kustomization.yaml
  docs/component-versions.md
Labels: lgtm, approved

#52 fix prettier error
  .gitignore
  .pre-commit-config.yaml
Labels: lgtm, approved
