Repository kserve/modelmesh-serving, pull requests merged in 2022-11, with the labels that each got.

#272 feat: Enable HA by default for Modelmesh Controller
  config/manager/manager.yaml
Labels: lgtm, approved

#271 feat: Support passing labels and annotations from ServingRuntimePodSpec to runtime Pod
  .github/workflows/run-fvt.yml
  .pre-commit-config.yaml
  Dockerfile.develop
  config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/bases/serving.kserve.io_servingruntimes.yaml
  controllers/modelmesh/runtime.go
  controllers/modelmesh/runtime_test.go
  controllers/modelmesh/util.go
  go.mod
  go.sum
  scripts/build_docker.sh
  scripts/deploy/iks/test-fvt.sh
Labels: approved

#276 feat: Supports image pull secrets
  config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/bases/serving.kserve.io_servingruntimes.yaml
  controllers/modelmesh/modelmesh.go
  controllers/modelmesh/runtime.go
  controllers/modelmesh/runtime_test.go
  controllers/modelmesh/util.go
  controllers/servingruntime_controller.go
  docs/configuration/README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved

#250 feat: TorchServe support
  .github/workflows/run-fvt.yml
  README.md
  config/default/config-defaults.yaml
  config/runtimes/kustomization.yaml
  config/runtimes/torchserve-0.x.yaml
  controllers/modelmesh/cluster_config.go
  controllers/servingruntime_controller_test.go
  controllers/testdata/servingruntime_controller.golden
  fvt/predictor/predictor_suite_test.go
  fvt/scaleToZero/scaleToZero_suite_test.go
  pkg/config/config.go
Labels: approved

#282 Add Rafael as a reviewer
  OWNERS
Labels: lgtm, approved

#277 docs: Update Custom Runtime Docs
  docs/runtimes/README.md
  docs/runtimes/mlserver_custom.md
Labels: documentation
