Repository kserve/modelmesh-serving, pull requests merged in 2022-09, with the labels that each got.

#220 feat: Make list of supported built-in runtime server types overridable
  config/default/config-defaults.yaml
  controllers/servingruntime_controller.go
  controllers/servingruntime_validator.go
  controllers/servingruntime_validator_test.go
  controllers/suite_test.go
  fvt/tls.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved

#227 feat: Pass ServingRuntime inference endpoint to built-in adapter
  controllers/modelmesh/runtime.go
  controllers/testdata/servingruntime_controller.golden
Labels: lgtm, approved

#236 doc: Update cluster sizing link in quickstart.md
  docs/quickstart.md
Labels: documentation, approved

#233 fix: Tolerate kustomize version 3.2
  docs/quickstart.md
  scripts/delete.sh
  scripts/install.sh
  scripts/setup_user_namespaces.sh
Labels: bug, lgtm, approved

#232 doc: fix port-forward command in run-inference.md
  docs/predictors/run-inference.md
  docs/quickstart.md
Labels: documentation, lgtm

#235 doc: Update FVT prerequisites
  fvt/README.md
Labels: documentation, lgtm, test

#238 chore: Add myself as a reviewer
  OWNERS
Labels: lgtm, approved

#234 chore: Preserve command history from `make develop` sessions
  .gitignore
  scripts/develop.sh
Labels: bug, lgtm

#237 chore: Add script to identify broken doc links
  Makefile
  docs/configuration/README.md
  docs/inference/data-types-mapping.md
  docs/model-formats/advanced-configuration.md
  docs/predictors/README.md
  docs/runtimes/custom_runtimes.md
  scripts/verify_doc_links.py
Labels: documentation, lgtm, approved, test

#245 docs: Reinstate Quickstart kustomize v4.0.0 prerequisite
  docs/quickstart.md
Labels: documentation, lgtm, approved

#244 chore: Fix error in `verify_doc_links.py` script
  scripts/verify_doc_links.py
Labels: lgtm, approved

#246 chore: Automatically set kube context in development container
  .gitignore
  docs/developer.md
  fvt/README.md
  scripts/develop.sh
Labels: lgtm, approved, test, development
