Repository kserve/modelmesh-serving, pull requests merged in 2023-08, with the labels that each got.

#414 doc: Update docs for release v0.11.0
  .github/workflows/fvt.yml
  controllers/modelmesh/modelmesh.go
  docs/component-versions.md
  docs/install/install-script.md
  docs/production-use/README.md
  docs/quickstart.md
  docs/release-process.md
  fvt/README.md
  scripts/setup_user_namespaces.sh
Labels: documentation, lgtm, approved

#412 release: Update ModelMesh image tags to v0.11.0
  .github/workflows/fvt.yml
  config/default/config-defaults.yaml
  config/dependencies/fvt.yaml
  config/dependencies/quickstart.yaml
  config/manager/kustomization.yaml
  docs/component-versions.md
  docs/install/install-script.md
  scripts/setup_user_namespaces.sh
Labels: lgtm

#415 chore: Rename webhook (HPA)
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  scripts/self-signed-ca.sh
Labels: lgtm

#416 release: Update KServe to v0.11.0
  config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/bases/serving.kserve.io_inferenceservices.yaml
  config/crd/bases/serving.kserve.io_servingruntimes.yaml
  go.mod
  go.sum
Labels: lgtm, approved

#417 release: Update KServe to v0.11.0
  config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/bases/serving.kserve.io_inferenceservices.yaml
  config/crd/bases/serving.kserve.io_servingruntimes.yaml
  go.mod
  go.sum
Labels: lgtm, approved

#373 Add Makefile documentation
  Makefile
  docs/developer.md
Labels: lgtm
