Repository kserve/modelmesh-serving, pull requests merged in 2023-09, with the labels that each got.

#421 fix: Skip `ClusterServingRuntime` deletion if deployed using `--namespace-scope-mode`
  scripts/delete.sh
  scripts/install.sh
Labels: lgtm

#429 test: Increase initial time to stabilize for FVTs
  fvt/fvtclient.go
  fvt/predictor/predictor_suite_test.go
  fvt/storage/storage_test.go
Labels: lgtm, test

#422 chore: use generic Set instead of deprecated sets.String
  .golangci.yaml
  controllers/modelmesh/constraints.go
  controllers/modelmesh/model_type_labels.go
  controllers/modelmesh/model_type_labels_test.go
  controllers/servingruntime_validator.go
Labels: lgtm

#400 fix: Update delete.sh to support self-sign-certs
  scripts/delete.sh
Labels: lgtm

#428 Support development version of Kustomize in install script
  scripts/delete.sh
  scripts/install.sh
  scripts/setup_user_namespaces.sh
Labels: lgtm

#397 fix: Goroutine memory leak
  controllers/service_controller.go
  controllers/util.go
Labels: lgtm

#437 chore: Add new approvers to OWNERS file
  OWNERS
Labels: lgtm, approved

#435 fix: namespace-scoped mode by service_controller
  controllers/service_controller.go
  controllers/util.go
Labels: bug, lgtm, approved
