Repository kserve/modelmesh-serving, pull requests merged in 2023-05, with the labels that each got.

#363 fix: Generalizes sed and fixes dry-run cmd
  scripts/install.sh
  scripts/self-signed-ca.sh
Labels: bug, lgtm, approved

#314 Push multi-arch images
  .github/workflows/build-and-push.yml
  .github/workflows/build.yml
  .github/workflows/fvt.yml
  .github/workflows/test.yml
  .github/workflows/unit-test.yml
  Dockerfile
  Dockerfile.develop
  Makefile
  config/manager/manager.yaml
  scripts/build_devimage.sh
  scripts/develop.sh
Labels: approved

#364 doc: Remove cert flag from quickstart
  docs/quickstart.md
Labels: bug, documentation

#368 Reduce FVT disk usage
  .github/workflows/fvt.yml
  fvt/predictor/predictor_test.go
Labels: approved, test

#371 Support ARM 64 bit architecture
  controllers/modelmesh/runtime.go
  controllers/testdata/servingruntime_controller.golden
Labels: approved

#361 chore: Update TorchServe to 0.7.1
  .github/workflows/fvt.yml
  config/runtimes/kustomization.yaml
Labels: lgtm, approved

#355 chore: Update MLServer to v1.3.2
  .github/workflows/fvt.yml
  config/runtimes/kustomization.yaml
  config/runtimes/mlserver-1.x.yaml
  config/samples/servingruntime_pullerless.yaml
  controllers/servingruntime_controller_test.go
  controllers/testdata/servingruntime_controller.golden
  docs/install/README.md
  docs/model-formats/advanced-configuration.md
  docs/monitoring.md
  docs/predictors/README.md
  docs/quickstart.md
  fvt/fvtclient.go
  fvt/hpa/hpa_test.go
  fvt/predictor/predictor_test.go
  fvt/scaleToZero/scale_to_zero_test.go
  fvt/storage/storage_test.go
  pkg/config/config_test.go
Labels: lgtm

#346 feat: Add Template Grafana Dashboard for ModelMesh Metrics
  config/dashboard/ModelMeshMetricsDashboard.json
  config/prometheus/servicemonitor.yaml
  docs/monitoring.md
Labels: enhancement, lgtm, approved

#359 chore: Update TritonServer to 23.04
  .github/workflows/fvt.yml
  config/runtimes/kustomization.yaml
  fvt/predictor/predictor_suite_test.go
  fvt/predictor/predictor_test.go
  fvt/testdata/predictors/tf-predictor.yaml
Labels: lgtm, approved
