Repository kserve/modelmesh-serving, pull requests merged in 2023-01, with the labels that each got.

#291 Update Dockerfile packages
  Dockerfile
  Dockerfile.develop
  go.mod
  go.sum
Labels: lgtm, approved

#296 release: Update image tags for `v0.10.0-rc0`
  config/default/config-defaults.yaml
  config/dependencies/quickstart.yaml
  config/manager/kustomization.yaml
  docs/component-versions.md
  docs/install/install-script.md
  go.mod
  go.sum
  scripts/setup_user_namespaces.sh
Labels: lgtm

#303 Update release version in quickstart.md
  docs/quickstart.md
Labels: lgtm, approved

#304 Use `--namespace-scope-mode` for Quickstart
  docs/install/install-script.md
  docs/quickstart.md
  scripts/install.sh
Labels: lgtm, approved

#309 release: Update `main` docs for version `v0.10.0`
  docs/component-versions.md
  docs/install/install-script.md
  scripts/setup_user_namespaces.sh
Labels: documentation, lgtm, approved

#308 release: Update `release-0.10` image tags for version `v0.10.0`
  config/default/config-defaults.yaml
  config/manager/kustomization.yaml
  docs/component-versions.md
  docs/install/install-script.md
  go.mod
  go.sum
  scripts/setup_user_namespaces.sh
Labels: approved

#306 doc: include namespace-scope info
  docs/install/install-script.md
Labels: documentation, lgtm, approved
