Repository kserve/modelmesh-serving, pull requests merged in 2024-01, with the labels that each got.

#470 chore: Update to Go 1.20, kserve v0.11.2
  .github/workflows/fvt-base.yml
  Dockerfile
  Dockerfile.develop
  config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/bases/serving.kserve.io_inferenceservices.yaml
  config/crd/bases/serving.kserve.io_servingruntimes.yaml
  go.mod
  go.sum
  scripts/deploy/iks/test-fvt.sh
Labels: approved

#466 docs: Update release-process.md
  docs/release-process.md
  scripts/fmt.sh
Labels: approved

#464 Update fvt toolchain (#463)
  .dockerignore
  .pre-commit-config.yaml
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  Dockerfile
  Dockerfile.develop
  controllers/suite_test.go
  pkg/predictor_source/inferenceservice_registry.go
  scripts/deploy/iks/build-image-dind.sh
  scripts/deploy/iks/deploy-mm-serving.sh
  scripts/deploy/iks/run-perf-test.sh
  scripts/deploy/iks/run-setup.sh
  scripts/deploy/iks/test-fvt.sh
  scripts/deploy/iks/undeploy-mm-serving.sh
  scripts/fmt.sh
Labels: approved

#475 release: Update `v0.11.2` image tags
  .github/workflows/build.yml
  .github/workflows/fvt-base.yml
  .github/workflows/fvt-cs.yml
  .github/workflows/fvt-ns.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  config/default/config-defaults.yaml
  config/dependencies/fvt.yaml
  config/dependencies/quickstart.yaml
  config/manager/kustomization.yaml
  docs/component-versions.md
  docs/install/install-script.md
  docs/quickstart.md
  scripts/setup_user_namespaces.sh
Labels: approved

#476 docs: Updates post release v0.11.2
  .gitignore
  docs/component-versions.md
  docs/install/install-script.md
  docs/quickstart.md
  docs/release-process.md
  scripts/setup_user_namespaces.sh
Labels: documentation, approved

#465 Replace "foo" string with a less generic one
  controllers/config/templating.go
Labels: lgtm, approved

#479 chore: Update protobuf to v1.32.0
  go.mod
  go.sum
Labels: lgtm, approved

#480 chore: Update dependencies
  go.mod
  go.sum
Labels: approved

#468 chore: Update indirect dependency to knative.dev/serving v0.37.5
  .golangci.yaml
  go.mod
  go.sum
  scripts/fmt.sh
Labels: approved

#487 chore: Upgrade to Go 1.21 (rebase developer image from ubi/go-toolset to ubi-minimal)
  Dockerfile.develop
  go.mod
  go.sum
Labels: approved
